EZGarage/EZGarage/Controllers/MngServicesController.cs
using EZGarage.Services.Contracts;
using EZGarage.Web.Helpers;
using EZGarage.Web.Models.MngServicesModels;
using EZGarage.Web.Models.MyServicesModels;
using EZGarage.Web.Models.VisitViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [EzAuhtorize(Role = "employee")]
    public class MngServicesController : Controller
    {
        /// <summary>
        /// Field
        /// </summary>
        private readonly IServiceService serviceService;
        private readonly IVisitService visitService;

        /// <summary>
        /// Ctor with service injection
        /// </summary>
        /// <param name="serviceService"></param>
        /// <param name="visitService"></param>

        public MngServicesController(IServiceService serviceService, IVisitService visitService)
        {
            this.serviceService = serviceService;
            this.visitService = visitService;
        }

        /// <summary>
        /// Index endpoint
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var services = await serviceService.GetManyAsync();
            var servicesVMs = services.Select(se => new ServiceViewModel(se));

            var mngServicesVM = new MngServicesIndexVM(servicesVMs);

            return View(mngServicesVM);
        }

        /// <summary>
        /// Post method for detailed view of single service
        /// </summary>
        /// <param name="id">Service Id</param>
        /// <param name="action"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        [HttpPost("single/{id}")]
        public async Task<IActionResult> Single(int id, string action, string context)
        {
            try
            {
                var service = await serviceService.GetOneByIdAsync(id);
                var visit = await visitService.GetOneByServiceId(id);
                var serviceVM = new ServiceViewModel(service);
                var visitVM = new VisitViewModel(visit);
                serviceVM.Action = action;
                var serviceAndVisitVM = new ServiceAndVisitVM(serviceVM, visitVM);


                return View(serviceAndVisitVM);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post method to advance status of service item
        /// </summary>
        /// <param name="id">Service Id</param>
        /// <returns></returns>
        [HttpPost("advance/{id}")]
        public async Task<IActionResult> Advance(int id)
        {
            string action = "advance";
            try
            {
                var service = await serviceService.AdvanceServiceAsync(id);
            }
            catch (Exception)
            {

                var serviceViewModel = await GetServiceVMById(id);
                var visitViewModel = await GetVisitVMByServiceId(id);

                serviceViewModel.Action = action;
                serviceViewModel.Context = "fail";

                var serviceAndVisitViewModel = new ServiceAndVisitVM(serviceViewModel, visitViewModel);

                return View("single", serviceAndVisitViewModel);
            }

            var serviceVM = await GetServiceVMById(id);
            var visitVM = await GetVisitVMByServiceId(id);
            serviceVM.Action = action;
            serviceVM.Context = "success";

            var serviceAndVisitVM = new ServiceAndVisitVM(serviceVM, visitVM);

            return View("single", serviceAndVisitVM);
        }

        /// <summary>
        /// Post method to delete service
        /// </summary>
        /// <param name="id">Service Id</param>
        /// <returns></returns>
        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var visitVM = await GetVisitVMByServiceId(id);

                await serviceService.DeleteAsync(id);

                ServiceViewModel serviceVM = new ServiceViewModel();
                serviceVM.Action = "delete";
                serviceVM.Context = "success";

                var serviceAndVisitVM = new ServiceAndVisitVM(serviceVM, visitVM);
                return View("single", serviceAndVisitVM);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }

        }

        /// <summary>
        /// Aux method to get service view model by service id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private async Task<ServiceViewModel> GetServiceVMById(int id)
        {
            var service = await serviceService.GetOneByIdAsync(id);
            return new ServiceViewModel(service);
        }

        /// <summary>
        /// Aux method to get visit by service id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private async Task<VisitViewModel> GetVisitVMByServiceId(int id)
        {
            var visit = await visitService.GetOneByServiceId(id);
            return new VisitViewModel(visit);
        }
    }
}

EZGarage/EZGarage/Controllers/MngVisitsController.cs
using EZGarage.Services.Contracts;
using EZGarage.Services.Dto.Visits;
using EZGarage.Web.Helpers;
using EZGarage.Web.Models.MngVisitsModels;
using EZGarage.Web.Models.ServiceItemModels;
using EZGarage.Web.Models.VehicleViewModels;
using EZGarage.Web.Models.VisitViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("/MngVisits")]
    [EzAuhtorize(Role = "employee")]
    public class MngVisitsController : Controller
    {
        /// <summary>
        /// Fields for calling injected services
        /// </summary>
        private readonly IVisitService visitService;
        private readonly IVehicleService vehicleService;
        private readonly IServiceService serviceService;
        private readonly IServiceItemService serviceItemService;

        /// <summary>
        /// ctor of controller
        /// </summary>
        /// <param name="visitService"></param>
        /// <param name="vehicleService"></param>
        /// <param name="serviceService"></param>
        /// <param name="serviceItemService"></param>
        public MngVisitsController(IVisitService visitService, IVehicleService vehicleService, IServiceService serviceService, IServiceItemService serviceItemService)
        {
            this.visitService = visitService;
            this.vehicleService = vehicleService;
            this.serviceService = serviceService;
            this.serviceItemService = serviceItemService;
        }

        /// <summary>
        /// Index View with all visits
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var visits = await visitService.GetAllAsync();
            var visitVMs = visits.Select(vi => new VisitViewModel(vi));



            return View(visitVMs);
        }

        /// <summary>
        /// Visists by customer ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet("{id}")]
        public async Task<IActionResult> GetCustomerVisits(int id)
        {
            try
            {
                var visits = await visitService.GetAllAsync();

                var visitVMs = visits.Where(vi => vi.CustomerId == id)
                    .Select(vi => new VisitViewModel(vi));

                return View(visitVMs);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }

        }

        /// <summary>
        /// Detailed visit view by Visit ID
        /// </summary>
        /// <param name="id"></param>
        /// <param name="action"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        [HttpPost("single/{id}")]
        public async Task<IActionResult> Single(int id, string action, string context)
        {
            try
            {
                var visit = await this.visitService.GetDetailedVisitAsync(id);
                var visitVM = new VisitDetailedViewModel(visit);
                visitVM.Action = action;
                visitVM.Context = context;

                return View(visitVM);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }

        }

        /// <summary>
        /// Calls the delete view (request and confirm) depeding on the string message
        /// </summary>
        /// <param name="id"></param>
        /// <param name="action"></param>
        /// <returns></returns>
        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(int id, string action)
        {
            try
            {
                if (action == "deleterequest")
                {
                    var visitVM = await this.GetVisitByIdAndAllServiceItems(id);

                    visitVM.Context = action;

                    return View(visitVM);
                }
                else
                {
                    await visitService.DeleteAsync(id);
                    var emptyVisitVM = new VisitAndServiceItemsVM();

                    emptyVisitVM.Context = action;

                    return View(emptyVisitVM);
                }
            }
            catch (Exception e)
            {
                var emptyVisitVMfail = new VisitAndServiceItemsVM();
                emptyVisitVMfail.Context = e.Message;

                return View(emptyVisitVMfail);
            }

        }

        /// <summary>
        /// Calls the view for adding services to a visit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost("{id}/addservices")]
        public async Task<IActionResult> AddServices(int id)
        {
            try
            {
                var visit = await visitService.GetDetailedVisitAsync(id);
                var visitVM = new VisitDetailedViewModel(visit);

                var serviceItems = await serviceItemService.GetAllAsync();
                var serviceitemVMs = serviceItems.Select(si => new ServiceItemViewModel(si));

                var visitServiceItemVM = new VisitAndServiceItemsVM(visitVM, serviceitemVMs);

                return View(visitServiceItemVM);
            }
            catch (Exception e)
            {

                return NotFound(e.Message);
            }

        }

        /// <summary>
        /// Performs the adding of a service and returns back to the calling View
        /// </summary>
        /// <param name="id"></param>
        /// <param name="serviceItemId"></param>
        /// <param name="statusId"></param>
        /// <param name="readyDate"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> ServiceAdder(int id, int serviceItemId, int statusId, string readyDate)
        {

            try
            {
                await this.serviceService.PostAsync(new Services.Dto.Services.PostServiceDto
                {
                    VisitId = id,
                    ServiceItemId = serviceItemId,
                    StatusId = statusId,
                    ReadyDate = readyDate
                });
            }
            catch (Exception e)
            {
                var visitAndServiceItems = await GetVisitByIdAndAllServiceItems(id);
                visitAndServiceItems.Context = "fail";
                visitAndServiceItems.Message = e.Message;

                return View("addservices", visitAndServiceItems);
            }

            try
            {
                var visitVMAndServiceItemsVMs = await GetVisitByIdAndAllServiceItems(id);
                visitVMAndServiceItemsVMs.Context = "success";

                return View("addservices", visitVMAndServiceItemsVMs);
            }
            catch (Exception e)
            {

                return NotFound(e.Message);
            }


        }

        /// <summary>
        /// Calls the form view for creating a visit
        /// </summary>
        /// <returns></returns>
        [HttpPost("createnew")]
        public async Task<IActionResult> CreateNew()
        {
            var serviceItems = await serviceItemService.GetAllAsync();
            var serviceItemVMs = serviceItems.Select(si => new ServiceItemViewModel(si));
            var vehicles = await vehicleService.GetAllAsync();
            var vehicleVMs = vehicles.Select(ve => new VehicleViewModel(ve));

            var createVisitFormVM = new CreateNewVisitFormVM(vehicleVMs, serviceItemVMs);

            return View(createVisitFormVM);
        }

        /// <summary>
        /// Performs the creation of the visit and return to a view with the newly created service
        /// </summary>
        /// <param name="vehicleId"></param>
        /// <param name="arrivalDate"></param>
        /// <param name="serviceItemIds"></param>
        /// <param name="readyDates"></param>
        /// <returns></returns>
        [HttpPost("visitcreator")]
        public async Task<IActionResult> VisitCreator(int vehicleId, string arrivalDate, string serviceItemIds, string readyDates)
        {
            int id;
            try
            {
                var serviceItemsIds = serviceItemIds.Trim().Split(" ").Select(x => int.Parse(x)).ToArray();
                var servicesFinishDates = readyDates.Trim().Split(" ");

                var vehicle = await this.vehicleService.GetOneByIdAsync(vehicleId);
                var customerId = vehicle.CustomerId;

                var request = new PostVisitDto
                {
                    CustomerId = customerId,
                    VehicleId = vehicleId,
                    ArrivalDate = arrivalDate,
                    ServiceIteIds = serviceItemsIds,
                    ServiceItemFinishDates = servicesFinishDates,
                    //ServiceItemFinishDates = readyDates,
                };

                var response = await this.visitService.PostAsync(request);
                id = response.Id;
            }
            catch (Exception e)
            {
                return View("ConfirmCreated", new CreateVisitVM(null, "fail", e.Message));
            }


            try
            {
                var visit = await this.visitService.GetDetailedVisitAsync(id);
                var visitVM = new VisitDetailedViewModel(visit);

                var createVisitVM = new CreateVisitVM(visitVM, "success", null);

                return View("ConfirmCreated", createVisitVM);
            }
            catch (Exception e)
            {

                return NotFound(e.Message);
            }

        }


        /// <summary>
        /// Aux method
        /// </summary>
        /// <param name="visitId"></param>
        /// <returns></returns>
        private async Task<VisitAndServiceItemsVM> GetVisitByIdAndAllServiceItems(int visitId)
        {

EZGarage/EZGarage/Views/MngVisits/AddServices.cshtml
@model VisitAndServiceItemsVM
@{
    var visit = Model.Visit;
    var serviceItemsDB = Model.ServiceItems.ToList();
    var customer = visit.CustomerName;

    var notStarted = "1 Not Started";
    var inProgress = "2 In Progress";
    var ready = "3 Ready";

    var context = Model.Context;
    var contextMessage = Model.Message;

}

<link rel="stylesheet" href="~/css/search.css" type="text/css" />
<style>
</style>

@if (context == "fail")
{
    <div class="alert alert-danger" role="alert">
        @contextMessage
    </div>
}
else if (context == "success")
{
    <div class="alert alert-primary" role="alert">
        Visit with ID @visit.Id successfully updated
    </div>
}

<style>
    .container-all {
        margin-bottom: 5%;
        margin-top: 5%;
    }
</style>

<div class="container-all">

    @{
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th>Visit ID</th>
                    <th>Vehicle ID</th>
                    <th>Visiting Vehicle</th>
                    <th>Owner ID</th>
                    <th>Owner</th>
                    <th>Number of Services</th>
                    <th>Arrival Date</th>
                    <th>Ready Date</th>
                </tr>
            </thead>
            <tr>
                <td>@visit.Id</td>
                <td>
                    @visit.VehicleId
                </td>
                <td>
                    @visit.VehicleMakeModel
                </td>
                <td>
                    @visit.CustomerId
                </td>
                <td>
                    @visit.CustomerName
                </td>
                <td>
                    @visit.Services.Count()
                </td>
                <td>
                    @visit.ArrivalDate
                </td>
                <td>
                    @visit.ReadyDate
                </td>
            </tr>
        </table>
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th>
                        Services Ordered
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Ready Date
                    </th>
                    <th>
                        Price
                    </th>
                </tr>
            </thead>
            @foreach (var service in visit.Services.OrderBy(se => se.ProgressBarPercent).ThenByDescending(se => se.ReadyDate))
            {

                <tr>
                    <td>
                        @service.ServiceItem
                    </td>
                    <td>
                        @service.Status
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: @service.ProgressBarPercent%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">@service.ProgressBarPercent%</div>
                        </div>
                    </td>
                    <td>
                        @service.ReadyDate
                    </td>
                    <td>
                        @service.Price @service.Currency
                    </td>
                </tr>
            }
        </table>
    }

    <form id="add-service" method="post" asp-controller="MngVisits" asp-action="ServiceAdder" asp-route-id="@visit.Id">
        <table class="table table-striped table-dark result-table-multiple">
            <thead>
                <tr>
                    <th>Service item ID</th>
                    <th>Status ID</th>
                    <th>Ready date</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="Service item ID" name="serviceItemId">
                    </td>
                    <td class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="1, 2 or 3" name="statusId">
                    </td>
                    <td class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="01-Jan-2021" name="readyDate">
                    </td>
                    <td>
                        <button type="submit" form="add-service" class="btn btn-primary">Add Service</button>
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th>
                        Service Items
                    </th>
                    <th>
                        Statuses
                    </th>
                </tr>

                @for (var i = 0; i < serviceItemsDB.Count(); i++)
                {
                    <tr>
                        <td>
                            @serviceItemsDB[i].Id @serviceItemsDB[i].Name
                        </td>
                        <td style="display:@(i <= 2 ? "": "none")">
                            @if (i == 0)
                            {
                                @notStarted
                            }
                            else if (i == 1)
                            {
                                @inProgress
                            }
                            else if (i == 2)
                            {
                                @ready
                            }
                        </td>
                    </tr>
                }
            </tfoot>
        </table>
    </form>


    <div>
        <a class="btn btn-primary btn-lg" asp-controller="MngVisits" asp-action="Index">
            Back to EZVisits
        </a>
    </div>

</div>


<script src="~/js/site.js"></script>

EZGarage/EZGarage/Views/MngVisits/ConfirmCreated.cshtml
@model CreateVisitVM
@{
    var visit = Model.Visit;
    var outcome = Model.Context;
    var message = Model.Message;


    if (outcome == "fail")
    {
        <div class="alert alert-danger" role="alert">
            @message
        </div>
    }
    else
    {
        <style>
            .container-all {
                margin-bottom: 5%;
                margin-top: 5%;
            }
        </style>

        <div class="container-all">

            <div class="alert alert-primary" role="alert">
                Visit with ID @visit.Id created
            </div>

            <table class="table table-striped table-dark ">

                <tr>
                    <th>Visit ID</th>
                    <th>Visiting Vehicle</th>
                    <th>Owner</th>
                    <th>Number of Services</th>
                    <th>Arrival Date</th>
                    <th>Ready Date</th>
                </tr>
                <tr>
                    <td>@visit.Id</td>
                    <td>
                        @visit.VehicleMakeModel
                    </td>
                    <td>
                        @visit.CustomerName
                    </td>
                    <td>
                        @visit.Services.Count()
                    </td>
                    <td>
                        @visit.ArrivalDate
                    </td>
                    <td>
                        @visit.ReadyDate
                    </td>
                </tr>
            </table>
            <table class="table table-striped table-dark ">
                <tr>
                    <th>
                        Services Ordered
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Ready Date
                    </th>
                    <th>
                        Price
                    </th>
                </tr>
                @foreach (var service in visit.Services)
                {

                    <tr>
                        <td>
                            @service.ServiceItem
                        </td>
                        <td>
                            @service.Status
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: @service.ProgressBarPercent%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">@service.ProgressBarPercent%</div>
                            </div>
                        </td>
                        <td>
                            @service.ReadyDate
                        </td>
                        <td>
                            @service.Price @service.Currency
                        </td>
                    </tr>
                }

                <tr>

                    <th>
                        <form method="post" asp-controller="MngVisits" asp-action="AddServices" asp-route-id="@visit.Id">

                            <button type="submit" class="btn btn-primary btn-lg">
                                Add Services to this Visit
                            </button>

                        </form>
                    </th>
                    <th>
                        <form method="post" asp-controller="MyVisits" asp-action="DetailedReport" asp-route-id="@visit.Id">

                            <button type="submit" class="btn btn-light btn-lg">
                                View Report
                            </button>

                        </form>
                    </th>
                    @*<th>
                        <form method="post" asp-controller="MyVisits" asp-action="DetailedReportBGN" asp-route-id="@visit.Id">

                            <button type="submit" class="btn btn-light btn-lg">
                                View Report (BGN)
                            </button>

                        </form>
                    </th>*@
                    <th>
                        <div>
                            Total:
                        </div>
                        <div>
                            @visit.Services.Select(se => se.Price).Sum() @visit.Currency
                        </div>
                    </th>
                </tr>
            </table>

            <div>
                <a class="btn btn-primary btn-lg" asp-controller="MngVisits" asp-action="Index">
                    Back to Visits
                </a>
            </div>
        </div>
    }
}

EZGarage/EZGarage/Views/MngVisits/GetCustomerVisits.cshtml
@model IEnumerable<VisitViewModel>
@{
    var visits = Model;
}

<style>
    .table {
        width =100%;
        border =1;
    }

    .bottom-container {
        display: flex
    }

    input {
        margin-top: 5%;
        margin-bottom: 1%;
    }


    .bottom-container {
        margin-bottom: 5%;
    }

    th:hover {
        cursor: pointer;
    }
</style>

<link rel="stylesheet" href="~/css/search.css" type="text/css" />
<script src="~/js/site.js"></script>




<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search">

<div class="container-all">

    @{
        <table class="table table-striped table-dark">

            <thead>
                <tr>
                    <th onclick="sortTable(0)">Visit ID</th>
                    <th onclick="sortTable(1)">Visiting Vehicle</th>
                    <th onclick="sortTable(2)">Owner</th>
                    <th onclick="sortTable(3)">Arrival Date</th>
                    <th onclick="sortTable(4)">Ready Date</th>
                    <th onclick="sortTable(5)">Status</th>
                </tr>
            </thead>
            <tbody id="myTableBody">
                @foreach (var visit in visits)
                {
                    <tr>
                        <td width="5%">
                            @visit.Id
                        </td>
                        <td>
                            @visit.VehicleMakeModel
                        </td>
                        <td>
                            @visit.CustomerName
                        </td>
                        <td>
                            @visit.ArrivalDate
                        </td>
                        <td>
                            @visit.DateAllDone
                        </td>

                        @{
                            if (visit.Services.All(se => se.Status.ToLower() == "ready"))
                            {
                                <td>
                                    Ready
                                </td>
                            }
                            else if (visit.Services.All(se => se.Status.ToLower() == "not started"))
                            {
                                <td>
                                    Not Started
                                </td>
                            }
                            else
                            {
                                <td>
                                    In Progress
                                </td>
                            }
                        }
                        <td>
                            <form method="post" asp-controller="MngVisits" asp-action="AddServices" asp-route-id="@visit.Id">
                                <button type="submit" class="btn btn-primary" value="advance" name="action">Add Services</button>
                            </form>
                        </td>
                        <td>
                            <form method="post" asp-controller="MngVisits" asp-action="Single" asp-route-id="@visit.Id">
                                <button type="submit" class="btn btn-light" value="advance" name="action">Details</button>
                            </form>
                        </td>
                        <td>
                            <form method="post" asp-controller="MngServices" asp-action="Single" asp-route-id="">
                                <button type="submit" class="btn btn-danger" value="advance" name="action">Delete</button>
                            </form>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    }

</div>

<div class="bottom-container">
    <a asp-controller="mngcustomers" asp-action="Index" class="btn btn-info btn-lg">
        Back To EZCustomers
    </a>
</div>