EZGarage/EZGarage/Controllers/MngVehiclesController.cs
using EZGarage.Services.Contracts;
using EZGarage.Services.Dto;
using EZGarage.Web.Helpers;
using EZGarage.Web.Models.MngVehiclesModels;
using EZGarage.Web.Models.Model_Manufacturer_VehType;
using EZGarage.Web.Models.VehicleViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("mngvehicles")]
    public class MngVehiclesController : Controller
    {
        /// <summary>
        /// Fields
        /// </summary>
        private readonly IVehicleService vehicleService;
        private readonly IManufacturerService manufacturerService;
        private readonly IModelService modelService;
        private readonly IVehicleTypeService vehicleTypeService;

        /// <summary>
        /// Ctor with services injections
        /// </summary>
        /// <param name="vehicleService"></param>
        /// <param name="manufacturerService"></param>
        /// <param name="modelService"></param>
        /// <param name="vehicleTypeService"></param>
        public MngVehiclesController(IVehicleService vehicleService,
            IManufacturerService manufacturerService,
            IModelService modelService,
            IVehicleTypeService vehicleTypeService)
        {
            this.vehicleService = vehicleService;
            this.manufacturerService = manufacturerService;
            this.modelService = modelService;
            this.vehicleTypeService = vehicleTypeService;
        }

        /// <summary>
        /// Index endpoint
        /// </summary>
        /// <param name="customerId">Customer Id</param>
        /// <param name="customerName">Customer Name</param>
        /// <param name="vehicleTypeId">Vehicle type Id</param>
        /// <param name="vehicleType">Vehicle type</param>
        /// <param name="modelId">Model Id</param>
        /// <param name="model">Model</param>
        /// <param name="manufacturerId">Manufacturer Id</param>
        /// <param name="manufacturer">Manufacturer</param>
        /// <param name="year">Year</param>
        /// <param name="regPlate">Registration plate</param>
        /// <returns></returns>
        [EzAuhtorize(Role = "employee")]
        [Route("index")]
        [HttpGet]
        public async Task<IActionResult> Index(int? customerId = null,
            string customerName = null,
            int? vehicleTypeId = null,
            string vehicleType = null,
            int? modelId = null,
            string model = null,
            int? manufacturerId = null,
            string manufacturer = null,
            int? year = null,
            string regPlate = null)
        {
            var matchingVehicles = await vehicleService.GetAllAsync(customerId, customerName, vehicleTypeId, vehicleType,
                modelId, model, manufacturerId, manufacturer, year, regPlate);

            var vehiclesVM = matchingVehicles.Select(ve => new VehicleViewModel(ve));

            var indexVM = new MngVehiclesIndexVM(null, vehiclesVM, null, null);

            return View(indexVM);
        }

        /// <summary>
        /// Get vehicle details method
        /// </summary>
        /// <param name="id">Vehicle Id</param>
        /// <returns></returns>
        [Route("vehicle/details/{id}")]
        [HttpGet]
        public async Task<IActionResult> GetVehicleDetails(int id)
        {
            var vehicle = await vehicleService.GetOneByIdAsync(id);
            var vehicleVM = new VehicleViewModel(vehicle);

            var indexVM = new MngVehiclesIndexVM(vehicleVM, null, "details", null);

            return View("index", indexVM);
        }

        /// <summary>
        /// Edit vehicle endpoint
        /// </summary>
        /// <param name="id"></param>
        /// <param name="regPlate"></param>
        /// <returns></returns>
        [Route("vehicle/edit/{id}")]
        [HttpPost]
        public async Task<IActionResult> EditVehicle(int id, string regPlate)
        {
            if (regPlate == null)
            {
                var vehicle = await vehicleService.GetOneByIdAsync(id);
                var vehicleVM = new VehicleViewModel(vehicle);

                var indexVM = new MngVehiclesIndexVM(vehicleVM, null, "edit", null);

                return View("index", indexVM);
            }
            else
            {
                var vehicle = await vehicleService.PutAsync(id, regPlate);
                var vehicleVM = new VehicleViewModel(vehicle);

                var indexVM = new MngVehiclesIndexVM(vehicleVM, null, "details", "editsuccess");

                return View("index", indexVM);
            }

        }

        /// <summary>
        /// Delete vehicle endpoint
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("vehicle/deletevehicleview/{id}")]
        [HttpGet]
        public async Task<IActionResult> DeleteVehicleView(int id)
        {
            var vehicle = await vehicleService.GetOneByIdAsync(id);
            var vehicleVM = new VehicleViewModel(vehicle);

            var indexVM = new MngVehiclesIndexVM(vehicleVM, null, "delete", "confirmdelete");

            return View("index", indexVM);
        }

        /// <summary>
        /// Delete vehicle confirmation endpoint
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost("/DeleteVehicleConfirmed")]
        public async Task<IActionResult> DeleteVehicleConfirmed(int id)
        {
            var result = await vehicleService.DeleteAsync(id);

            var vehicles = await vehicleService.GetAllAsync();

            var vehiclesVM = vehicles.Select(ve => new VehicleViewModel(ve));
            var indexVM = new MngVehiclesIndexVM(null, vehiclesVM, null, "deletesuccess");

            return View("index", indexVM);
        }

        /// <summary>
        /// Create new vehicle model endpoint
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CreateNewModel()
        {
            var registerVehicleNewVM = await this.GetRegisterNewModelVMAsync(null);

            return View("RegisterNewModel", registerVehicleNewVM);
        }

        /// <summary>
        /// Register new model endpoint
        /// </summary>
        /// <param name="modelName"></param>
        /// <param name="manufacturerId"></param>
        /// <returns></returns>
        [HttpPost("RegisterNewModel")]
        public async Task<IActionResult> RegisterNewModel(string modelName, int manufacturerId)
        {
            ModelDto model;
            try
            {
                model = await modelService.PostAsync(modelName, manufacturerId);
            }
            catch (Exception e)
            {
                var registerNewModelVM = await this.GetRegisterNewModelVMAsync(e.Message);

                return View("RegisterNewModel", registerNewModelVM);
            }

            var vehicles = await vehicleService.GetAllAsync();
            var vehicleVMs = vehicles.Select(ve => new VehicleViewModel(ve));

            var indexVM = new MngVehiclesIndexVM(null, vehicleVMs, $"{model.Name} {model.Manufacturer}", "modelRegistered");

            return View("index", indexVM);
        }

        /// <summary>
        /// Register new manufacturer endpoint
        /// </summary>
        /// <param name="manufacturerName"></param>
        /// <returns></returns>
        [HttpPost("RegisterNewManufacturer")]
        public async Task<IActionResult> RegisterNewManufacturer(string manufacturerName)
        {
            var manufacturer = await manufacturerService.PostAsync(manufacturerName);

            if (manufacturer == null)
            {
                var registerNewModelVMFail = await this.GetRegisterNewModelVMAsync("Already existing manufacturer");

                return View("RegisterNewModel", registerNewModelVMFail);
            }

            var registerNewModelVMsucc = await this.GetRegisterNewModelVMAsync("manufSuccess");

            return View("RegisterNewModel", registerNewModelVMsucc);
        }

        /// <summary>
        /// Private method to assist with registering new model
        /// </summary>
        /// <param name="message"></param>
        /// <returns></returns>
        [HttpGet]
        private async Task<RegisterNewModelVM> GetRegisterNewModelVMAsync(string message)
        {
            var models = await modelService.GetAllAsync();
            var manufacturers = await manufacturerService.GetAllAsync();

            var registerNewModelVM = new RegisterNewModelVM(models.Select(mo => new ModelVM(mo)).ToList(), manufacturers.Select(ma => new ManufacturerVM(ma)).ToList(), message);

            return registerNewModelVM;
        }

        /// <summary>
        /// Get vehicles for given customer endpoint
        /// </summary>
        /// <param name="customerId">Customer Id</param>
        /// <returns></returns>
        [HttpGet("vehicles/{customerId}")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> GetCustomerVehicles(int customerId)
        {
            try
            {
                var matchingVehicles = await this.vehicleService.GetVehiclesByCustomerIdAsync(customerId);

                var vehiclesVM = matchingVehicles.Select(ve => new VehicleViewModel(ve));
                var result = new MngVehiclesIndexVM(null, vehiclesVM, null, null);

                return View("Index", result);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Get manufacturer models endpoint
        /// </summary>
        /// <param name="id">Manufacturer Id</param>
        /// <returns></returns>
        [HttpGet("manufacturermodels/{id}")]

EZGarage/EZGarage/Views/MngVehicles/Index.cshtml
@model MngVehiclesIndexVM


<style>
    .list-group-container {
        display: flex;
    }

    .entitled {
        font-size: 1.25em;
    }

    .search-field {
        flex-grow: 1;
        height: 45px;
    }


    th:hover {
        cursor: pointer;
    }
</style>
<link rel="stylesheet" href="~/css/search.css" type="text/css" />


@{
    var areMultpleInBundle = Model.VehicleVMs != null;
    var isSingleInBundle = Model.VehicleVM != null;
    var vehicles = Model.VehicleVMs;

    if (Model.Context == "deletesuccess")
    {
        <div class="alert alert-success" role="alert">
            Vehicle deleted successfully
        </div>
    }
    else if (Model.Context == "modelRegistered")
    {
        <div class="alert alert-success" role="alert">
            Vehicle Model Registered: @Model.Purpose
        </div>
    }
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    @if (isSingleInBundle == true)
    {
        <div class="result-container">
            <div class="tab-pane" id="tab3" role="tabpanel">
                <a type="button" class="btn btn-primary btn-lg" asp-controller="MngVehicles" asp-action="CreateNewModel">Create New Model</a>
            </div>

            <br />
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search">
        </div>
    }



    @if (areMultpleInBundle == true)
    {
        <div class="tab-pane" id="tab3" role="tabpanel">
            <a type="button" class="btn btn-primary btn-lg btn-block" asp-controller="MngVehicles" asp-action="CreateNewModel">Create New Model</a>
        </div>
        <br />
        <div class="result-container">
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search">
            <table class="table table-striped table-dark result-table-multiple">
                <thead>
                    <tr>
                        <th onclick="sortTable(0)">ID</th>
                        <th onclick="sortTable(1)">Model</th>
                        <th onclick="sortTable(2)">Manufacturer</th>
                        <th onclick="sortTable(3)">Owner ID</th>
                        <th onclick="sortTable(4)">Owner name</th>
                        <th onclick="sortTable(5)">Year</th>
                        <th onclick="sortTable(6)">Reg. Plate</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="myTableBody">
                    @foreach (var instance in vehicles)
                    {
                        <tr>
                            <td>
                                @instance.Id
                            </td>
                            <td>
                                @instance.Model
                            </td>
                            <td>
                                @instance.Manufacturer
                            </td>
                            <td>
                                @instance.CustomerId
                            </td>
                            <td>
                                @instance.CustomerName
                            </td>
                            <td>
                                @instance.Year
                            </td>
                            <td>
                                @instance.RegistrationPlate
                            </td>
                            <td>
                                <a type="button" class="btn btn-info" asp-controller="MngVehicles" asp-action="GetVehicleDetails" asp-route-id="@instance.Id">Details</a>
                            </td>
                            <td>
                                <form method="post" asp-controller="MngVehicles" asp-action="EditVehicle" asp-route-id="@instance.Id">
                                    <button type="submit" class="btn btn-secondary">Edit</button>
                                </form>
                            </td>
                            <td>
                                <a type="button" class="btn btn-danger" asp-controller="MngVehicles" asp-action="DeleteVehicleView" asp-route-id="@instance.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else /*will trigger if only 1 vehicle*/
    {

        var vehicle = Model.VehicleVM;
        var purpose = Model.Purpose;

        <table class="table table-striped table-dark result-table-multiple">
            <thead>
                <tr>
                    <th>Vehicle ID</th>
                    <th>Model ID</th>
                    <th>Model</th>
                    <th>Manuf ID</th>
                    <th>Manufacturer</th>
                    <th>Vehicle Type ID</th>
                    <th>Vehicle Type</th>
                    <th>Owner ID</th>
                    <th>Owner name</th>
                    <th>Year</th>
                    <th>Reg. plate</th>
                    <th></th>
                </tr>
            </thead>

            @if (purpose == "details")
            {
                <tbody id="myTableBody">
                    <tr>
                        <td>
                            @vehicle.Id
                        </td>
                        <td>
                            @vehicle.ModelId
                        </td>
                        <td>
                            @vehicle.Model
                        </td>
                        <td>
                            @vehicle.ManufacturerId
                        </td>
                        <td>
                            @vehicle.Manufacturer
                        </td>
                        <td>
                            @vehicle.VehicleTypeId
                        </td>
                        <td>
                            @vehicle.VehicleType
                        </td>
                        <td>
                            @vehicle.CustomerId
                        </td>
                        <td>
                            @vehicle.CustomerName
                        </td>
                        <td>
                            @vehicle.Year
                        </td>
                        <td>
                            @vehicle.RegistrationPlate
                        </td>
                        <td>
                            <form method="post" asp-controller="MngVehicles" asp-action="EditVehicle" asp-route-id="@vehicle.Id">
                                <button type="submit" class="btn btn-primary">Edit</button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            }
            @if (purpose == "edit")
            {
                <tbody id="myTableBody">
                    <tr>
                        <td>
                            @vehicle.Id
                        </td>
                        <td>
                            @vehicle.ModelId
                        </td>
                        <td>
                            @vehicle.Model
                        </td>
                        <td>
                            @vehicle.ManufacturerId
                        </td>
                        <td>
                            @vehicle.Manufacturer
                        </td>
                        <td>
                            @vehicle.VehicleTypeId
                        </td>
                        <td>
                            @vehicle.VehicleType
                        </td>
                        <td>
                            @vehicle.CustomerId
                        </td>
                        <td>
                            @vehicle.CustomerName
                        </td>
                        <td>
                            @vehicle.Year
                        </td>
                        <td>
                            <form id="edit-form" asp-controller="MngVehicles" asp-action="EditVehicle">
                                <input type="text" class="form-control" id="floatingInput" placeholder="@vehicle.RegistrationPlate" name="regPlate">
                            </form>
                        </td>
                        <td>
                            <button type="submit" form="edit-form" class="btn btn-primary">Submit</button>
                        </td>
                    </tr>
                </tbody>

            }
            @if (purpose == "delete")
            {
                <tbody id="myTableBody">
                    <tr>
                        <td>
                            @vehicle.Id
                        </td>
                        <td>
                            @vehicle.ModelId
                        </td>
                        <td>
                            @vehicle.Model
                        </td>
                        <td>
                            @vehicle.ManufacturerId
                        </td>
                        <td>
                            @vehicle.Manufacturer
                        </td>
                        <td>
                            @vehicle.VehicleTypeId
                        </td>
                        <td>
                            @vehicle.VehicleType
                        </td>
                        <td>
                            @vehicle.CustomerId
                        </td>
                        <td>
                            @vehicle.CustomerName
                        </td>
                        <td>
                            @vehicle.Year
                        </td>
                        <td>
                            @vehicle.RegistrationPlate
                        </td>
                        <td>
                            <form asp-controller="MngVehicles" asp-action="DeleteVehicleConfirmed" asp-route-id="@vehicle.Id">
                                <button type="submit" class="btn btn-danger">Delete</button>

                            </form>
                        </td>
                    </tr>
                </tbody>

            }

        </table>
        if (Model.Context == "editsuccess")
        {
            <div class="alert alert-success" role="alert">
                Vehicle edited successfully
            </div>
        }

        if (Model.Context == "confirmdelete")
        {
            <div class="alert alert-warning" role="alert">
                You are about to delete this vehicle
            </div>
        }


    }


    @if (Model.Context == null && Model.Purpose == null)
    {
        <div>
            <a class="btn btn-primary btn-lg" asp-controller="Home" asp-action="Index">
                Back to Home
            </a>
            <a asp-controller="mngcustomers" asp-action="Index" class="btn btn-info btn-lg">
                Back To Customers
            </a>
        </div>
    }
    else
    {
        <div>
            <a class="btn btn-primary btn-lg" asp-controller="MngVehicles" asp-action="Index">
                Back to EZVehicles
            </a>
        </div>

    }

</body>
</html>
<script src="~/js/site.js"></script>

EZGarage/EZGarage/Views/MngVehicles/RegisterNewModel.cshtml
@model RegisterNewModelVM
@{ var manufacturers = Model.Manufacturers;
    var message = Model.Message; }

<div class="alert alert-primary" role="alert">
    Create new model. Fields are required.
</div>
@{ 
    if (message != null)
    {
        if (message == "manufSuccess")
        {
        <div class="alert alert-success" role="alert">
            Manufacturer registered
        </div> 
        }
        else
        {
        <div class="alert alert-danger" role="alert">
            @message
        </div> 
        }
    } 
}

<form id="create-model" method="post" asp-controller="MngVehicles" asp-action="RegisterNewModel">
    <table class="table table-striped table-dark result-table-multiple">
        <thead>
            <tr>
                <th>Model Name</th>
                <th>Manufacturer ID</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="form-floating mb-3">
                    <input type="text" class="form-control"  placeholder="Model Name" name="modelName">
                </td>
                <td class="form-floating mb-3">
                    <input type="text" class="form-control" placeholder="Manufacturer ID" name="manufacturerID">
                </td>
                <td>
                    <button type="submit" form="create-model" class="btn btn-primary">Register New Model</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<form id="create-manufacturer" method="post" asp-controller="MngVehicles" asp-action="RegisterNewManufacturer">
    <table class="table table-striped table-dark result-table-multiple">
        <thead>
            <tr>
                <th>Manufacturer Name</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="Manufacturer name" name="manufacturerName">
                </td>
                <td>
                    <button type="submit" form="create-manufacturer" class="btn btn-primary">Register new manufacturer</button>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Manufacturer
                </th>
            </tr>
            @foreach (var manufacturer in manufacturers)
            {
            <tr>
                <td>
                    @manufacturer.Id
                </td>
                <td>
                    @manufacturer.Name
                </td>
            </tr>
            }
        </tfoot>
    </table>
</form>