EZGarage/EZGarage/Controllers/MyServicesController.cs
using EZGarage.Services.Contracts;
using EZGarage.Web.Models.MyServicesModels;
using EZGarage.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("myservices")]
    public class MyServicesController : Controller
    {
        /// <summary>
        /// Fields
        /// </summary>
        private readonly IServiceService serviceService;
        private readonly IUserService userService;

        /// <summary>
        /// Ctor with service injections
        /// </summary>
        /// <param name="serviceService"></param>
        /// <param name="userService"></param>
        public MyServicesController(IServiceService serviceService, IUserService userService)
        {
            this.serviceService = serviceService;
            this.userService = userService;
        }

        /// <summary>
        /// Index ednpoint to get services of customer 
        /// </summary>
        /// <param name="id">Customer Id</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        public async Task<IActionResult> Index(int id)
        {
            try
            {
                var userServiceDtos = await this.serviceService.GetManyAsync(id);

                var customerDto = await this.userService.GetOneCustomerAsync(id);

                var customerVM = new CustomerViewModel(customerDto);
                var serviceVMs = userServiceDtos.Select(se => new ServiceViewModel(se));

                var indexViewModel = new MyServicesIndexViewModel(customerVM, serviceVMs);

                return View(indexViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Filter by date post endpoint
        /// </summary>
        /// <param name="datefrom"></param>
        /// <param name="dateto"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> FilterByDate(string datefrom = null, string dateto = null)
        {
            try
            {
                var customerId = HttpContext.Session.GetInt32("id");
                var customerDto = await this.userService.GetOneCustomerAsync((int)customerId);
                var filteredServices = await this.serviceService.GetManyAsync(customerId, null, null, null, null, null, null, null, null, null, datefrom, dateto);

                var customerVM = new CustomerViewModel(customerDto);
                var serviceVMs = filteredServices.Select(se => new ServiceViewModel(se));

                var indexViewModel = new MyServicesIndexViewModel(customerVM, serviceVMs);

                return View("Index", indexViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }
    }
}

EZGarage/EZGarage/Views/MyServices/Index.cshtml
@model MyServicesIndexViewModel
@{
    var customer = Model.Customer;
    var customerServices = Model.Services;
}

<link rel="stylesheet" href="~/css/search.css" type="text/css" />
<style>
    form.date-form {
        margin-bottom: 25px;
    }

        form.date-form div {
            display: flex;
        }

        form.date-form span {
            width: 22%;
            margin: 0px 15px 0px 0px;
            /*padding: 0px 0px -30px 0px;*/
        }
    th:hover {
        cursor: pointer;
    }
</style>

<div style="margin:20px;">
    <h1 style="font-size:1.25rem; margin: 25px;"> List of services for @customer.Name: </h1>
    <div asp-validation-summary="ModelOnly"></div>
    <form class="date-form" method="post" asp-controller="MyServices" asp-action="FilterByDate">
        <div>

            <span class="form-floating mb-3">
                <label for="floatingInput">Visit Date From</label>
                <input id="Textbox" class="form-control" type="text" placeholder="01-jan-2021" name="datefrom">
            </span>
            <span class="form-floating">
                <label for="floatingInput">Visit Date Up To</label>
                <input id="Textbox" class="form-control" type="text" placeholder="01-jan-2021" name="dateto">
            </span>
        </div>
        <div class="button-div">
            <button type="submit" class="btn btn-primary btn-lg">Filter by Date</button>
        </div>
    </form>



    <br />
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search">

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th onclick="sortTable(0)">Vehicle</th>
                <th onclick="sortTable(1)">Service</th>
                <th onclick="sortTable(2)">Status</th>
                <th onclick="sortTable(3)">Visit Date</th>
                <th onclick="sortTable(4)">Ready Date</th>
                <th onclick="sortTable(5)">Price in BGN</th>
            </tr>
        </thead>
        <tbody id="myTableBody">
            @{
                foreach (var service in customerServices.OrderBy(se => Convert.ToDateTime(se.VisitArrivalDate)))
                {
                    <tr>
                        <td>
                            @service.VehicleMakeModel
                        </td>
                        <td>
                            @service.ServiceItem
                        </td>
                        <td>
                            @service.Status
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: @service.ProgressBarPercent%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">@service.ProgressBarPercent%</div>
                            </div>
                        </td>
                        <td>
                            @service.VisitArrivalDate
                        </td>
                        <td>
                            @service.ReadyDate
                        </td>
                        <td>
                            @service.Price
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-action="Index" type="btn submit" class="btn btn-primary btn-lg">
        Back To My Services
    </a>

</div>

<script src="~/js/site.js"></script>