EZGarage/EZGarage/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class AboutUsController : Controller
    {
        /// <summary>
        /// Index endpoint
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }
    }
}

EZGarage/EZGarage/Controllers/MyVehiclesController.cs
using EZGarage.Services.Contracts;
using EZGarage.Web.Models.MyVehiclesModels;
using EZGarage.Web.Models.UserViewModels;
using EZGarage.Web.Models.VehicleViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("myvehicles")]
    public class MyVehiclesController : Controller
    {
        /// <summary>
        /// Fields
        /// </summary>
        private readonly IVehicleService vehicleService;
        private readonly IUserService userService;

        /// <summary>
        /// Ctor with service injections
        /// </summary>
        /// <param name="vehicleService"></param>
        /// <param name="userService"></param>
        public MyVehiclesController(IVehicleService vehicleService, IUserService userService)
        {
            this.vehicleService = vehicleService;
            this.userService = userService;
        }

        /// <summary>
        /// Index endpoint to show visits of customer
        /// </summary>
        /// <param name="id">Customer Id</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        public async Task<IActionResult> IndexAsync(int id)
        {
            try
            {
                var customer = await this.userService.GetOneCustomerAsync(id);
                var customerVehicles = await this.vehicleService.GetAllAsync(id);

                var customerVM = new CustomerViewModel(customer);
                var vehiclesVM = customerVehicles.Select(ve => new VehicleViewModel(ve));

                var vehiclesIndexModel = new MyVehiclesIndexViewModel(customerVM, vehiclesVM);

                return View(vehiclesIndexModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }

        }
    }
}

EZGarage/EZGarage/Controllers/MyVisitsController.cs
using EZGarage.Services.Contracts;
using EZGarage.Web.Models.MyVisitsModels;
using EZGarage.Web.Models.UserViewModels;
using EZGarage.Web.Models.VisitViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("myvisits")]
    public class MyVisitsController : Controller
    {
        /// <summary>
        /// Fields
        /// </summary>
        private readonly IUserService userService;
        private readonly IVisitService visitService;
        private readonly IHostingEnvironment hostingEnvironment;

        /// <summary>
        /// Ctor with service injections
        /// </summary>
        /// <param name="userService">User service</param>
        /// <param name="visitService">Visit service</param>
        /// <param name="hostingEnvironment">Hosting environment</param>
        public MyVisitsController(IUserService userService, IVisitService visitService, IHostingEnvironment hostingEnvironment)
        {
            this.userService = userService;
            this.visitService = visitService;
            this.hostingEnvironment = hostingEnvironment;
        }

        /// <summary>
        /// Index endpoint
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet("{id}")]
        public async Task<IActionResult> Index(int id)
        {
            try
            {
                var customer = await this.userService.GetOneCustomerAsync(id);
                var customerVisits = await this.visitService.GetAllAsync(id);

                var customerViewModel = new CustomerViewModel(customer);
                var customerVisitsViewModel = customerVisits.Select(vi => new VisitDetailedViewModel(vi));

                var indexViewModel = new MyVisitsIndexViewModel(customerViewModel, customerVisitsViewModel);

                return View(indexViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post method to view detailed visit report in base currency
        /// </summary>
        /// <param name="id">Visit Id</param>
        /// <returns></returns>
        [HttpPost("detailedreportbgn/{id}")]
        public async Task<IActionResult> DetailedReportBGN(int id)
        {
            try
            {
                var visit = await this.visitService.GetDetailedVisitAsync(id);

                var visitViewModel = new VisitDetailedViewModel(visit);

                return View(visitViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }


        /// <summary>
        /// Get method for downloading report without forex
        /// </summary>
        /// <param name="id">Visit Id</param>
        /// <returns></returns>
        [HttpGet("downloadvisitreportbgn/{id}")]
        public async Task<IActionResult> DownloadVisitReport(int id)
        {
            try
            {
                var visit = await this.visitService.GetDetailedVisitAsync(id);

                var visitViewModel = new VisitDetailedViewModel(visit);
                visitViewModel.ReportCurrency = visit.Currency;
                visitViewModel.ReportCurrencyPrice = visit.TotalPrice.ToString();

                return View(visitViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post method to create pdf report for visit without currency
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost("PDFproviderbgn/{id}")]
        public IActionResult PDFproviderBGN(int id)
        {
            try
            {
                HtmlToPdfConverter converter = new HtmlToPdfConverter();
                WebKitConverterSettings settings = new WebKitConverterSettings();
                settings.WebKitPath = Path.Combine(hostingEnvironment.ContentRootPath, @"Syncfusion\QtBinariesWindows");
                converter.ConverterSettings = settings;

                var stringRoute = "http://localhost:5000/myvisits/downloadvisitreportbgn/" + $"{id}";
                PdfDocument document = converter.Convert(stringRoute);

                MemoryStream ms = new MemoryStream();
                document.Save(ms);
                document.Close(true);
                ms.Position = 0;

                FileStreamResult fileStreamResult = new FileStreamResult(ms, "application/pdf");
                fileStreamResult.FileDownloadName = ("Report.pdf");

                return fileStreamResult;
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post method to view detailed visit report
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost("detailedreport/{id}")]
        public async Task<IActionResult> DetailedReport(int id)
        {
            try
            {
                var visit = await this.visitService.GetDetailedVisitAsync(id);

                var visitViewModel = new VisitDetailedViewModel(visit);

                return View(visitViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Get method for downloading report with forex
        /// </summary>
        /// <param name="id">Visit Id</param>
        /// <param name="reportCurrency">Report selected currency</param>
        /// <param name="reportAmount">Report converted amount</param>
        /// <returns></returns>
        [HttpGet("downloadvisitreport/{id}/currency/{reportCurrency}/amount/{reportAmount}")]
        public async Task<IActionResult> DownloadVisitReport(int id, string reportCurrency, string reportAmount)
        {
            try
            {
                var visit = await this.visitService.GetDetailedVisitAsync(id);

                var visitViewModel = new VisitDetailedViewModel(visit);
                visitViewModel.ReportCurrency = reportCurrency;
                visitViewModel.ReportCurrencyPrice = reportAmount;

                return View(visitViewModel);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post method to create pdf report for visit with currency
        /// </summary>
        /// <param name="id"></param>
        /// <param name="forexCurrency"></param>
        /// <param name="forexPrice"></param>
        /// <returns></returns>
        [HttpPost("PDFprovider/{id}")]
        public IActionResult PDFprovider(int id, string forexCurrency, string forexPrice)
        {
            //HTML to PDF conversion code.
            try
            {
                HtmlToPdfConverter converter = new HtmlToPdfConverter();
                WebKitConverterSettings settings = new WebKitConverterSettings();
                settings.WebKitPath = Path.Combine(hostingEnvironment.ContentRootPath, @"Syncfusion\QtBinariesWindows");
                converter.ConverterSettings = settings;

                var stringRoute = "http://localhost:5000/myvisits/downloadvisitreport/" + $"{id}" + "/currency/" + $"{forexCurrency}" + " /amount/" + $"{forexPrice}";
                PdfDocument document = converter.Convert(stringRoute);

                MemoryStream ms = new MemoryStream();
                document.Save(ms);
                document.Close(true);
                ms.Position = 0;

                FileStreamResult fileStreamResult = new FileStreamResult(ms, "application/pdf");
                fileStreamResult.FileDownloadName = ("Report.pdf");

                return fileStreamResult;
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

    }
}

EZGarage/EZGarage/Controllers/ServicesController.cs
using AutoMapper;
using EZGarage.Services.Contracts;
using EZGarage.Services.Dto.ServiceItems;
using EZGarage.Web.Helpers;
using EZGarage.Web.Models.ServiceItemModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EZGarage.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("services")]
    public class ServicesController : Controller
    {
        /// <summary>
        /// Service item service and mapper fields
        /// </summary>
        private readonly IServiceItemService serviceItemService;
        private readonly IMapper mapper;

        /// <summary>
        /// Ctor with injections
        /// </summary>
        /// <param name="serviceItemService">Service item service</param>
        /// <param name="mapper">Automapper</param>
        public ServicesController(IServiceItemService serviceItemService,
            IMapper mapper)
        {
            this.serviceItemService = serviceItemService;
            this.mapper = mapper;
        }

        /// <summary>
        /// Main index page get method
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var services = await this.serviceItemService.GetAllAsync();

                var result = new ServiceItemsViewModel(services);

                return View(result);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Service item details get method
        /// </summary>
        /// <param name="id">Service item Id</param>
        /// <returns></returns>
        [HttpGet("details/{id}")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var serviceItem = await serviceItemService.GetOneByIdAsync(id);

                var result = new ServiceItemViewModel(serviceItem);

                return View(result);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Search method
        /// </summary>
        /// <param name="name">Service item name</param>
        /// <returns></returns>
        //[Authorize(Roles = "1")]
        [HttpGet("search")]
        public async Task<IActionResult> Search([FromQuery] string name)
        {
            try
            {
                var foundSerivceItems = await serviceItemService.GetManyAsync(name, null, null);

                if (foundSerivceItems.Count() != 0)
                {
                    ICollection<ServiceItemViewModel> result = new List<ServiceItemViewModel>();
                    foreach (var item in foundSerivceItems)
                    {
                        result.Add(new ServiceItemViewModel(item));
                    }
                    return View(result);
                }
                else
                {
                    return NotFound("No match");
                }
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Get method to create service item
        /// </summary>
        /// <returns></returns>
        [HttpGet("create")]
        [EzAuhtorize(Role = "employee")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Post method for creating a new service item
        /// </summary>
        /// <param name="serviceItem"></param>
        /// <returns></returns>
        [HttpPost("create")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> Create(ServiceItemViewModel serviceItem)
        {
            try
            {
                var serviceItemDto = this.mapper.Map<PostServiceItemDto>(serviceItem);
                var result = await this.serviceItemService.PostAsync(serviceItemDto);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Get method to edit an existing service item
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet("edit/{id}")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            try
            {
                var serviceItem = await this.serviceItemService.GetOneByIdAsync(id);

                var item = this.mapper.Map<ServiceItemViewModel>(serviceItem);

                return View("Edit", item);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post item for editing an existing service item
        /// </summary>
        /// <param name="serviceItemInputViewModel"></param>
        /// <returns></returns>
        [HttpPost("edit/{id}")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> Edit(ServiceItemInputViewModel serviceItemInputViewModel)
        {
            try
            {
                var item = this.mapper.Map<ServiceItemDto>(serviceItemInputViewModel);

                var serviceItem = await this.serviceItemService.PutAsync(item);

                var result = new ServiceItemViewModel(serviceItem);
                result.IsSuccessful = true;

                return View(result);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Get method to delete service item by id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet("delete/{id}")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var serviceItem = await this.serviceItemService.GetOneByIdAsync(id);

                var item = this.mapper.Map<ServiceItemViewModel>(serviceItem);

                return View(item);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        /// <summary>
        /// Post method for deleting an existing item by id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost("delete/{id}")]
        [EzAuhtorize(Role = "employee")]
        public async Task<IActionResult> DeleteForm([FromRoute] int id)
        {
            try
            {
                await this.serviceItemService.DeleteAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }
    }
}

EZGarage/EZGarage/Views/Shared/_Layout.cshtml
@{
    var sessionUserRole = Context.Session.GetString("role");
    var sessionUserName = Context.Session.GetString("user");
    var sessionUserId = Context.Session.GetInt32("id");
    var sessionViewMode = Context.Session.GetString("viewMode");

    var isUserLogged = sessionUserRole != null;
    var isEmployeeLogged = sessionUserRole == "employee";

    var isEmployeeMode = sessionViewMode == "employee";

    var employeeColor = "#10c9c9";
    var userColor = "#08ED30";
    var blackColor = "#000000";
    var darkgrayColor = "#222222";
    var midgrayColor = "#777b7e";
    var lightgrayColor = "#999da0";
    var whiteColor = "#FFFFFF";

    var brandColor = isEmployeeMode ? employeeColor : userColor;

    var bannerLogoUrl = isEmployeeMode
        ? "https://ezgarage.blob.core.windows.net/logotrasnparent/logo_verticalslim_employee.png"
        : "https://ezgarage.blob.core.windows.net/logotrasnparent/logo_verticalslim_normal.png";

    var bannerLogoFooterUrl = isEmployeeMode
        ? "https://ezgarage.blob.core.windows.net/logotrasnparent/logo_text_emp.png"
        : "https://ezgarage.blob.core.windows.net/logotrasnparent/logo_text_default.png";

    var userLogoLightgrayUrl = "https://ezgarage.blob.core.windows.net/usericontransparent/usericon_lightgray.png";
    var userLogoGreenUrl = "https://ezgarage.blob.core.windows.net/usericontransparent/usericon_user.png";
    var userLogoCyantUrl = "https://ezgarage.blob.core.windows.net/usericontransparent/usericon_emp.png";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] EZGarage</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />

    @if (isEmployeeMode)
    {
        <link rel="stylesheet" href="~/css/custom_cyan.css" />
    }
    else
    {
        <link rel="stylesheet" href="~/css/custom_green.css" />
    }

    <style>
        * {
            margin: 0;
            padding: 0;
        }

        dl, ol, ul {
            margin: 0;
        }

        html {
            height: 100%;
        }

        body {
            display: flex;
            flex-direction: column;
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            font-size: 1rem;
            font-weight: 400;
            background: @blackColor;
            background-image: url(https://wallpapercave.com/wp/wp53625.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            color: @lightgrayColor;
        }

        body::after{
            opacity: 0.5;
        }

        header {
            height: 70px;
            display: flex;
            background-color: @darkgrayColor;
            justify-content: flex-start;
            align-items: center;
            border-bottom: 1px solid @lightgrayColor;
        }

            header .banner-logo {
                margin-left: 15px;
            }

                header .banner-logo img {
                    height: auto;
                    width: auto;
                    max-height: 60px;
                    max-width: 250px;
                }

        header nav {
                display: flex;
                flex-grow: 1;
                padding-left:15px;
                padding-right:15px;
        }

            header ul {
                display: flex;
                flex-grow: 1;
                list-style-type: none;
            }

            header a {
                color: @lightgrayColor;
            }

            header li:hover a {
                color:@brandColor;
            }

            header li.right{
                margin-left:auto;
            }

            header .user-profile {
                margin-left: 15px;
            }

                header .user-profile img {
                    height: auto;
                    width: auto;
                    max-height: 35px;
                    max-width: 35px;
                }

            header + div.content {
                flex-grow: 1;
            }

            /*dropdowns*/
            .dropdown .dropdown-toggle:hover{
                color:@brandColor!important;
            }

            .dropdown .dropdown-menu{
                background-color:@lightgrayColor;
            }

            .drawer{
                background-color:inherit !important;
                color:@blackColor!important;
            }
            .drawer:hover{
                background-color:@darkgrayColor !important;
                color:@brandColor!important;
            }

            #use-logo-corner:hover{
                content: url(@(isEmployeeMode? userLogoCyantUrl: userLogoGreenUrl))
            }

            #view-switch{
                margin-left:auto;
            }

        .customer-visit-report-table thead tr td{
            font-weight:400;
            font-size:1.33em;
        }

        footer {
            background-color: @darkgrayColor;
            height: 35px;
            border-top: 1px solid @lightgrayColor;
        }

        .centered {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .dropdown .dropdown-toggle {
            cursor: pointer;
        }
    </style>
</head>

<body>
    <header>
        <a class="banner-logo" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="@bannerLogoUrl" alt="Logo" style=" ">
        </a>

        <nav>
            <ul>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Services" asp-action="Index">Services</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="AboutUs" asp-action="Index">About Us</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                </li>

                @if (isUserLogged && !isEmployeeMode)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                            My Garage
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item drawer" asp-controller="MyServices" asp-action="Index" asp-route-id="@sessionUserId">
                                My Services
                            </a>
                            <a class="dropdown-item drawer" asp-controller="MyVehicles" asp-action="Index" asp-route-id="@sessionUserId">
                                My Vehicles
                            </a>

                            <a class="dropdown-item drawer" asp-controller="MyVisits" asp-action="Index" asp-route-id="@sessionUserId">
                                My Visits
                            </a>
                        </div>
                    </li>
                }
                @if (isEmployeeMode)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                            Employee Panel
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item drawer" asp-controller="MngCustomers" asp-action="Index">
                                EZCustomers
                            </a>
                            <a class="dropdown-item drawer" asp-controller="MngServices" asp-action="Index">
                                EZServices
                            </a>
                            <a class="dropdown-item drawer" asp-controller="MngVehicles" asp-action="Index">
                                EZVehicles
                            </a>
                            <a class="dropdown-item drawer" asp-controller="MngVisits" asp-action="Index">
                                EZVisits
                            </a>
                        </div>
                    </li>
                }

                @if (!isUserLogged)
                {
                    <li class="nav-item right">
                        <a class="nav-link" asp-controller="Account" asp-action="Index">Login</a>
                    </li>
                }
                else
                {
                    @if (isEmployeeLogged)
                    {
                        <li class="nav-item right">
                            <form id="view-switch" class="nav-link right custom-control custom-switch" asp-controller="Home" asp-action="ChangeView" method="post">
                                <input type="checkbox" class="custom-control-input" style="cursor:pointer" @(isEmployeeMode ? "checked" : "") id="customSwitch4" onchange="$('form#view-switch').submit();" name="checkbox" />
                                <label class="custom-control-label" style="cursor:pointer" for="customSwitch4">@(sessionViewMode == "employee" ? "Employee Mode: On" : "Employee Mode: Off")</label>
                                <span class="text-primary" id="valueOfSwitch4"></span>
                            </form>
                        </li>
                    }
                    <li class="nav-item dropdown @(isEmployeeLogged?"centered" : "right")">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                            @sessionUserName
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item drawer" asp-controller="Account" asp-action="Logout">
                                Logout
                            </a>
                        </div>
                    </li>
                }

            </ul>
        </nav>
    </header>

    <div class="content container">
        <div class="row justify-content-center">
            <main role="main" class="col-12 pt-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer>
        <div class="container">
            &copy; 2021 -
            <img src=@bannerLogoFooterUrl alt="Logo" style="height: auto; width: auto; max-height: 110px; max-width: 110px; " /> -
            <a class="verticalallignmid" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>